version: '3'
services:
  web:
    build:
      context: ./docker/construct_web
      dockerfile: Dockerfile-web
    image: st-nginx
    container_name: st-nginx
    ports:
      - 8080:80

  app:
    build:
      context: ./docker/construct_app
      dockerfile: Dockerfile-app
    image: st-nodejs
    container_name: st-nodejs
    ports:
      - 3000:3000
    volumes:
      - ./myapp:/src
    command: [sh, -c, npm install && npm start]