version: '3'
services:
  web:
    image: nginx
    container_name: "st-nginx"
    volumes:
      - .:/usr/share/nginx/html
    ports:
      - "8080:80"

  app:
    build:
      context: ./docker/construct_app
      dockerfile: Dockerfile-app
    image: nodejs
    container_name: st-nodejs
    ports:
      - 3000:3000
    volumes:
      - ./myapp:/src
    command: [sh, -c, npm install && npm start]